name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    # Download and setup ngrok
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Setup RDP access
    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - name: Enable Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Configure RDP Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Set Admin Password
      run: Set-LocalUser -Name "admin" -Password (ConvertTo-SecureString -AsPlainText "Giogio20064." -Force)

    # Additional setup: Install Git and configure repository
    - name: Install Git (if not present)
      run: choco install git -y --no-progress || echo "Git may already be installed"

    - name: Configure Git user
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    # Option 1: Simple copy of repository to a specific location
    - name: Copy repository to desired location
      run: |
        $targetPath = "C:\MyApp"
        if (Test-Path $targetPath) {
            Remove-Item $targetPath -Recurse -Force
        }
        Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination $targetPath -Recurse -Force
        Write-Host "Repository copied to $targetPath"

    # Option 2: Clone repository directly (alternative approach)
    - name: Clone repository to persistent location
      run: |
        $repoPath = "C:\MyApp"
        $githubToken = "${{ secrets.GITHUB_TOKEN }}"
        $repoUrl = "https://$githubToken@github.com/${{ github.repository }}.git"
        
        if (Test-Path $repoPath) {
            Set-Location $repoPath
            git pull origin main
        } else {
            git clone $repoUrl $repoPath
        }

    # Create ngrok tunnel (this should be the last step as it runs continuously)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
